### ISSUE TITLE
Data To-Do V 0.9

### ISSUE THREAD

**Issue by Ailoso** [abrahamYG/SC2plusSCBW#5]
### Data To-Do
- [ ] All Vespene Extractors for the three races fail to hide the Geyser underneath, showing it back up during the final part of the birth process 
- [ ] Several UI icons are missing commonly used in Observer interfaces
- [ ] Several Standard Hotkey Profile Issues
- [ ] Missing water ripples, High templar, Goliath, Vulture, Firebat, Lurker, Defiler
- [x] Unit/LifeArmorName/None has “Terran Vehicle Plating” text
- [ ] Missing defense radius actors for Missile turret, Photon Cannon, Sunken colony
- [ ] Different style on requirement tooltip CommandTooltipRequirements_BWTe for BWTe race, should be left justify

**Terran**
- [ ] Add Adjutant Lighting
- [ ] Physics Lab, Control tower, Covert Ops, Nuclear Silo, Machine Shop, cannot cancel research from the command card
- [x] SCV’s have auto repair enabled by default
- [ ] Nukes have no physics reactions
- [ ] No fire squibs get attached to target when firebat attacks
- [ ] Spider mines dont target dark templars
- [ ] Restoration visual effect plays too fast imo, also should it scale based on model size? I would move the visual down slightly too
- [ ] SCV’s can repair protoss units
- [x] Vulture has no death sounds
- [ ] Burrowed spider mine has the structure attribute, while unburrowed it doesn’t (can’t be stasised or stormed not sure if this was possible in sc1)
- [ ] Attached addon Letter don’t match what they are attached to
- [ ] Review building Subgroup Priority

Tactical AI
- [x] Add filter to ScienceVessels to use EMP against Shielded Units

Scanner Sweep
- [ ] The radius icon actor gets put on the Comsat station location

Control Tower
- [ ] Control tower origin position is underground during construction

Siege Tank
- [ ] Reminder to round up damage on the Tank
- [ ] Siege Tank Sieged Death won't inherit lookat point
- [ ] Siege Tank radii are seemingly larger than a regular Siege Tank

Ghost
- [ ] Update Nuke Launch and Land Timings

Physics Lab
- [ ] Seems to still play death detached at all times

**Zerg**
- [ ] Set Weak/Strong Values
- [ ] Review Zerg Portrait Lights
- [ ] Add Score values for MP
- [x] Defiler gives 50 minerals when burrowing
- [x] Lurker has mismatch cost with burrowed unit
- [ ] Ultralisks shouldn't be able to burrow (Core)
- [ ] Lurker, devourer, guardian morphs can't cancel once started, cancel refunds should be 100%, if killed refund 0%
- [ ] Muta morphs will take the money while decelerating: change to allow movement
- [ ] Muta and hydra morphs don’t respect facing (sc1 this is the case but should it be recreated?)
- [ ] Lair, Hive, Sunken, Spore, Spire morphs shouldn’t refund if killed
- [ ] Infested Terran Structure Attack toggle buttons mention banelings
- [ ] No physics reactions on Infested Terran suicide 
- [ ] Defiler Consume shouldn't be able to consume Larva
- [ ] If tech restrictions are disabled you cant place nydus canal exits
- [ ] Starting and then canceling lair/Hive morph causes the morph animation to keep playing indefinitely or cause the animations become bugged (Hatchery looking like a Lair)
- [ ] Drone Return cargo ability does not work
- [ ] Review building Subgroup Priority

Infested Command Center
- [ ] Infested CC needs a new Portrait
- [ ] If you infest an command center, the attached comsat/nuclear silo stays usable even if the cc lifted
- [ ] Infested Command center uses the worker rally point color for infested terrans

**Protoss**
- [ ] Set Weak/Strong Values
- [ ] Add Score values for MP
- [ ] Verify and Update Cargo Starting amount for Carrier and Reaver
- [ ] Recall visual doesn't play sound if no targets hit. (both on target and at arbiter location)
- [ ] Recalling units should appear where at the location of the arbiter not where it was cast.
- [ ] Recall radius seems too large
- [ ] When trying to shield battery restore something with full shield or target that is already being restored you get ‘Error’ message
- [ ] Stasis targets can be cloaked and decloaked by arbiter

Zealot
- [ ] Attack Sounds do not play

Halluciations
- [ ] Zealot Plays Death Sound
- [ ] Dragoon Plays Death Sound
- [ ] Marine Plays Death Sound
- [ ] Overlord Plays Death Sound
- [ ] Mutalisk Plays Death Sound
- [ ] Queen Plays Death Sound
